server {
    listen 80;

    #static admin files
    location ^~ /admin/frontend/ {
        alias /var/www/admin-frontend/;
        index dashboard.html;
        try_files $uri $uri/ =404;
    }

    #node api
    location /admin {
        rewrite ^/admin/?(.*)$ /$1 break;

        proxy_pass http://admin:4000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    #php app
    location / {
        proxy_pass http://php:80;
        proxy_set_header Host $host;
    }
}
